### ISSUE TITLE
Sensors flip when two bad coils are entered

### ISSUE THREAD

**Issue by neurofractal** [Macquarie-MEG-Research/MEMES#7]
Seems to be an error (?) or bug in ft_transform_geometry

**Comment by neurofractal** [comment]
![screen shot 2018-10-03 at 11 51 32 am](https://user-images.githubusercontent.com/18535653/46386072-b8daa900-c702-11e8-9607-6417977c9f46.png)

**Comment by paulsowman** [comment]
Does this mean you sometimes get the error and sometimes not? P

**Comment by neurofractal** [comment]
@paulsowman Yes... I think it's when two adjacent coils are bad, resulting in the remaining three coils being aligned --> poor rot3d fit. I'll cross-reference with results from MEG160 and do some investigating!

**Comment by neurofractal** [comment]
![screen shot 2018-10-03 at 4 40 15 pm](https://user-images.githubusercontent.com/18535653/46394171-9c9f3200-c72b-11e8-8e53-e4692419bab9.png)

See: [https://github.com/Macquarie-MEG-Research/MEMES/commit/cbbb4d2ae26600bb4199c1541120fba37e63a8f8](https://github.com/Macquarie-MEG-Research/MEMES/commit/cbbb4d2ae26600bb4199c1541120fba37e63a8f8)

This shows the MEG sensors for one participant realigned using 5 markers (rot3dfit method) and 3 markers (new ICP method). There is some difference (obviously) but not a lot 👍
